### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by reiyasawada** [reiyasawada/furima-38151#20]
# 自身のフリマアプリのURL | 本番環境(Heroku)のURL
https://furima-38151.herokuapp.com/
# Basic認証のIDとパスワード |  
admin
2222
# 出品者用のメールアドレスとパスワード | 本番環境で使用可能なユーザーの情報
techcamp10@icloud.com
saisyuukadai1
# 購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
techcamp12@icloud.com
saisyuukadai2

**Comment by maru2628** [comment]
@reiyasawada さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能**
- [ ] **「商品の編集」のボタンを押すと下記のようなエラーが出ておりますので、編集画面に遷移するようにしましょう。**
<img width="617" alt="スクリーンショット 2022-11-05 9 54 44" src="https://user-images.githubusercontent.com/116065064/200093776-552bdc1b-3541-4add-b517-cff360357319.png">


**商品削除機能**
- [ ] **「削除」のボタンを押すと下記のようなエラーが出ておりますので、削除の処理がされるようにしましょう。**
<img width="603" alt="スクリーンショット 2022-11-05 9 56 29" src="https://user-images.githubusercontent.com/116065064/200093848-551dd985-4ae3-41b0-96ce-d4f10709c4b1.png">



修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motomuun** [comment]
@reiyasawada さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/65059944/200095075-1bc24032-e71b-49c2-94de-a800d05bc5c8.png)
